name: Book

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: Book
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Setup mdbook
        uses: peaceiris/actions-mdbook@v2
      - uses: Swatinem/rust-cache@v2
      - run: cargo install mdbook-keeper
      - run: cd docs && mdbook build
      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v4
        with:
          path: 'docs/book'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
